version = 0.1
[default.deploy.parameters]
stack_name = "LinkedinToWhatsapp"
resolve_s3 = true
s3_prefix = "LinkedinToWhatsapp"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["LinkedintoWhatsapp=248189920167.dkr.ecr.us-east-1.amazonaws.com/linkedintowhatsapp2b1f79ab/linkedintowhatsappbe4fefc0repo", "WorkerFunction=248189920167.dkr.ecr.us-east-1.amazonaws.com/linkedintowhatsapp2b1f79ab/workerfunction5fd3ab0brepo"]
